import { execSync } from "child_process";
import esbuild from "esbuild";
import { copyFileSync, existsSync, mkdirSync, rmSync, writeFileSync } from "fs";
import { builtinModules } from "module";
import process from "process";

import pkg from "./package.json" with { type: "json" };

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
${pkg.homepage}
*/
`;

const prod = process.argv[2] === "production";
const devVaultPath = process.env.VAULT_ROOT;
const devVaultPluginDir = `${process.env.VAULT_ROOT}/.obsidian/plugins`;
const devPath = `${devVaultPluginDir}/${pkg.name}`;
const hotReloadPath = `${devVaultPluginDir}/hot-reload`;

function cloneHotReload(repoUrl) {
  console.log("Cloning hot-reload plugin...");
  try {
    execSync(`git clone "${repoUrl}" "${hotReloadPath}"`, {
      stdio: "inherit",
    });
  }
  catch (err) {
    console.error("Error cloning hot-reload plugin:", err.message);
  }
}

function copyToDevVault() {
  if (!devVaultPath) {
    return;
  }

  try {
    mkdirSync(devPath, { recursive: true });
    copyFileSync("main.js", `${devPath}/main.js`);
    copyFileSync("styles.css", `${devPath}/styles.css`);
    copyFileSync("manifest.json", `${devPath}/manifest.json`);
    writeFileSync(`${devPath}/.hotreload`, "");

    execSync(`touch "${devPath}/main.js"`, { stdio: "pipe" });

    console.log("Copied to dev vault:", devPath);
  }
  catch (err) {
    console.error("Error copying to dev vault:", err.message);
  }
}

/**
 * Ensures the hot-reload plugin is installed in the vault
 * Clones or pulls the repository as needed
 */
function ensureHotReloadPlugin() {
  if (!process.env.VAULT_ROOT) {
    return;
  }

  const gitDir = `${hotReloadPath}/.git`;
  const hotReloadRepo = "https://github.com/pjeby/hot-reload.git";

  if (existsSync(gitDir)) {
    try {
      execSync("git rev-parse --git-dir", {
        cwd: hotReloadPath,
        stdio: "pipe",
      });

      console.log("Pulling latest hot-reload changes...");
      execSync("git pull", {
        cwd: hotReloadPath,
        stdio: "inherit",
      });
    }
    catch {
      console.log("Hot-reload git directory corrupted, re-cloning...");
      rmSync(hotReloadPath, { force: true, recursive: true });
      cloneHotReload(hotReloadRepo);
    }
  }
  else if (!existsSync(`${hotReloadPath}/main.js`)) {
    cloneHotReload(hotReloadRepo);
  }
}

const copyPlugin = {
  name: "copy-to-dev-vault",
  setup(build) {
    build.onEnd(() => {
      if (!prod && devVaultPath) {
        copyToDevVault();
      }
    });
  },
};

const context = await esbuild.context({
  banner: {
    js: banner,
  },
  bundle: true,
  entryPoints: ["main.ts"],
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    ...builtinModules,
  ],
  format: "cjs",
  logLevel: "info",
  minify: prod,
  outfile: "main.js",
  plugins: [copyPlugin],
  sourcemap: prod ? false : "inline",
  target: "es2018",
  treeShaking: true,
});

if (prod) {
  await context.rebuild();
  process.exit(0);
}
else {
  console.log({ devPath, devVaultPath, hotReloadPath, pkgName: pkg.name });
  if (!devVaultPath) {
    console.group("⚠️  Development vault not set ⚠️");
    console.warn("VAULT_ROOT env variable not set ");
    console.warn("files will only build locally");
    console.warn(
      "Create a .env file with VAULT_ROOT to auto-copy to your vault",
    );
    console.groupEnd();
  }
  else {
    ensureHotReloadPlugin();
  }
  await context.watch();
}
