import esbuild from "esbuild";
import { execSync } from "node:child_process";
import {
  copyFileSync,
  existsSync,
  mkdirSync,
  rmSync,
  writeFileSync,
} from "node:fs";
import { builtinModules } from "node:module";
import process from "node:process";

import pkg from "./package.json" with { type: "json" };

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
${pkg.homepage}
*/
`;

const production = process.argv[2] === "production";
const developmentVaultPath = process.env.VAULT_ROOT;
const developmentVaultPluginDirectory = `${process.env.VAULT_ROOT}/.obsidian/plugins`;
const developmentPath = `${developmentVaultPluginDirectory}/${pkg.name}`;
const hotReloadPath = `${developmentVaultPluginDirectory}/hot-reload`;

function cloneHotReload(repoUrl) {
  console.log("Cloning hot-reload plugin...");
  try {
    execSync(`git clone "${repoUrl}" "${hotReloadPath}"`, {
      stdio: "inherit",
    });
  } catch (error) {
    console.error("Error cloning hot-reload plugin:", error.message);
  }
}

function copyToDevelopmentVault() {
  if (!developmentVaultPath) {
    return;
  }

  try {
    mkdirSync(developmentPath, { recursive: true });
    copyFileSync("main.js", `${developmentPath}/main.js`);
    copyFileSync("styles.css", `${developmentPath}/styles.css`);
    copyFileSync("manifest.json", `${developmentPath}/manifest.json`);
    writeFileSync(`${developmentPath}/.hotreload`, "");

    execSync(`touch "${developmentPath}/main.js"`, { stdio: "pipe" });

    console.log("Copied to dev vault:", developmentPath);
  } catch (error) {
    console.error("Error copying to dev vault:", error.message);
  }
}

/**
 * Ensures the hot-reload plugin is installed in the vault
 * Clones or pulls the repository as needed
 */
function ensureHotReloadPlugin() {
  if (!process.env.VAULT_ROOT) {
    return;
  }

  const gitDirectory = `${hotReloadPath}/.git`;
  const hotReloadRepo = "https://github.com/pjeby/hot-reload.git";

  if (existsSync(gitDirectory)) {
    try {
      execSync("git rev-parse --git-dir", {
        cwd: hotReloadPath,
        stdio: "pipe",
      });

      console.log("Pulling latest hot-reload changes...");
      execSync("git pull", {
        cwd: hotReloadPath,
        stdio: "inherit",
      });
    } catch {
      console.log("Hot-reload git directory corrupted, re-cloning...");
      rmSync(hotReloadPath, { force: true, recursive: true });
      cloneHotReload(hotReloadRepo);
    }
  } else if (!existsSync(`${hotReloadPath}/main.js`)) {
    cloneHotReload(hotReloadRepo);
  }
}

const copyPlugin = {
  name: "copy-to-dev-vault",
  setup(build) {
    build.onEnd(() => {
      if (!production && developmentVaultPath) {
        copyToDevelopmentVault();
      }
    });
  },
};

const context = await esbuild.context({
  banner: {
    js: banner,
  },
  bundle: true,
  entryPoints: ["main.ts"],
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    ...builtinModules,
  ],
  format: "cjs",
  logLevel: "info",
  minify: production,
  outfile: "main.js",
  plugins: [copyPlugin],
  sourcemap: production ? false : "inline",
  target: "es2018",
  treeShaking: true,
});

if (production) {
  await context.rebuild();
  process.exit(0);
} else {
  if (developmentVaultPath) {
    ensureHotReloadPlugin();
  } else {
    console.group("⚠️  Development vault not set ⚠️");
    console.warn("VAULT_ROOT env variable not set ");
    console.warn("files will only build locally");
    console.warn(
      "Create a .env file with VAULT_ROOT to auto-copy to your vault",
    );
    console.groupEnd();
  }
  await context.watch();
}
