name: Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels:
  - enhancement
assignees:
  - snelling-a
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Before submitting, please check the [Roadmap](https://github.com/snelling-a/obsidian-song-of-the-day/blob/main/docs/ROADMAP.md) to see if it's already planned.

  - type: textarea
    id: problem
    attributes:
      label: Problem or Use Case
      description: Is your feature request related to a problem? Please describe the use case.
      placeholder: I'm always frustrated when... / I would like to be able to...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see
      placeholder: What should the feature do? How should it work?
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions or workarounds?
      placeholder: What other approaches have you thought about?

  - type: dropdown
    id: contribution
    attributes:
      label: Would you like to contribute?
      description: Are you willing to help implement this feature?
      options:
        - "Yes, I'd like to contribute"
        - "No, just requesting"
        - "Maybe, need guidance"
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or examples about the feature request
