import builtins from "builtin-modules";
import dotenv from "dotenv";
import esbuild from "esbuild";
import { copyFileSync, existsSync, mkdirSync, writeFileSync } from "fs";
import { join } from "path";
import process from "process";

import pkg from "../package.json" with { type: "json" };
import { generateManifest } from "./generate-manifest.mjs";

dotenv.config();

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
${pkg.repository.url}
*/
`;

const prod = process.argv[2] === "production";

const devVaultPath = process.env.PATH_TO_DEV_VAULT;
let outdir = "dist";
let outputToVault = false;

if (devVaultPath && !prod) {
  const pluginDir = join(devVaultPath, ".obsidian", "plugins", pkg.name);
  outdir = pluginDir;
  outputToVault = true;

  if (!existsSync(pluginDir)) {
    mkdirSync(pluginDir, { recursive: true });
    console.log(`Created plugin directory: ${pluginDir}`);
  }
} else if (!existsSync(outdir)) {
  mkdirSync(outdir, { recursive: true });
}

const context = await esbuild.context({
  banner: {
    js: banner,
  },
  bundle: true,
  entryPoints: ["src/main.ts"],
  external: [
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    "electron",
    "obsidian",
    ...builtins,
  ],
  format: "cjs",
  logLevel: "info",
  minify: prod,
  outfile: join(outdir, "main.js"),
  sourcemap: prod ? false : "inline",
  target: "es2018",
  treeShaking: true,
});

// Helper function to write build artifacts
function writeArtifacts(dir) {
  // Generate and write manifest.json
  const manifestPath = join(dir, "manifest.json");
  writeFileSync(manifestPath, generateManifest());
  console.log(`✓ Generated ${manifestPath}`);

  // Copy styles.css if it exists
  const stylesSrc = "styles.css";
  if (existsSync(stylesSrc)) {
    const stylesDest = join(dir, "styles.css");
    copyFileSync(stylesSrc, stylesDest);
    console.log(`✓ Copied ${stylesSrc} to ${stylesDest}`);
  }
}

// Copy manifest.json and styles.css to output directory for dev vault
if (outputToVault) {
  writeArtifacts(outdir);

  // Create .hotreload marker file for hot-reload plugin
  const hotreloadMarker = join(outdir, ".hotreload");
  if (!existsSync(hotreloadMarker)) {
    writeFileSync(hotreloadMarker, "");
    console.log(`✓ Created .hotreload marker file`);
  }
}

if (prod) {
  await context.rebuild();
  // Write artifacts to production output directory
  writeArtifacts(outdir);
  process.exit(0);
} else {
  await context.watch();
  // Write artifacts for dev builds too
  if (!outputToVault) {
    writeArtifacts(outdir);
  }
  console.log(
    outputToVault
      ? `Watching for changes... Building to ${outdir}`
      : `Watching for changes... Building to ${outdir} (set PATH_TO_DEV_VAULT in .env to output to vault)`,
  );
}
